//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int ID_Karte { get; set; }
        public string Sediste { get; set; }
        public string Red { get; set; }
        public System.DateTime Datum { get; set; }
        public double Cena { get; set; }
        public int ID_Sale { get; set; }
        public int ID_Pozorista { get; set; }
        public int ID_Predstave { get; set; }
        public Nullable<int> GledalacRBR { get; set; }
    
        public virtual Igra Igra { get; set; }
        public virtual Gledalac Gledalac { get; set; }
    }
}
