//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Napisao
    {
        public int ID_Scenariste { get; set; }
        public int ID_Predstave { get; set; }
    
        public virtual Scenarista Scenarista { get; set; }
        public virtual Predstava Predstava { get; set; }
    }
}
