//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PozoristeDbContainer : DbContext
    {
        public PozoristeDbContainer()
            : base("name=PozoristeDbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pozoriste> Pozorista { get; set; }
        public virtual DbSet<Predstava> Predstave { get; set; }
        public virtual DbSet<Organizuje> OrganizujeN { get; set; }
        public virtual DbSet<Sala> Sale { get; set; }
        public virtual DbSet<Igra> IgraN { get; set; }
        public virtual DbSet<Scenarista> Scenaristi { get; set; }
        public virtual DbSet<Glumac> Glumci { get; set; }
        public virtual DbSet<Napisao> NapisaoN { get; set; }
        public virtual DbSet<Glumi> GlumioN { get; set; }
        public virtual DbSet<Karta> Karte { get; set; }
        public virtual DbSet<LoyaltyClan> LoyaltyClanovi { get; set; }
        public virtual DbSet<Gledalac> Gledaoci { get; set; }
    }
}
